plugins { id 'com.android.application' }

android {
    namespace 'com.bvjfjtutidut.app'
    compileSdk 34
    defaultConfig {
        applicationId "com.bvjfjtutidut.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName ""
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}
