plugins { id 'com.android.application' }

android {
    namespace 'com.myname.app'
    compileSdk 34
    defaultConfig {
        applicationId "com.myname.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}
